#cloud-config

runcmd:
  - curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash
  - mv spin /usr/local/bin/spin
  - chmod 755 /usr/local/bin/spin
write_files:
  - path: /etc/systemd/system/spin.service
    content: |
      [Unit]
      Description = Spin application
      After = network.target

      [Service]
      Type = simple
      # The app you want to install
      ExecStart = /usr/local/bin/spin up --from ghcr.io/technosophos/my-spin-app --listen 0.0.0.0:80
      # For anything but testing, User and Group should be single-purpose Spin users.
      User = root
      Group = root
      Restart = on-failure
      RestartSec = 5
      TimeoutStartSec = infinity

      [Install]
      WantedBy = multi-user.target
runcmd:
  - systemctl daemon-reload
  - systemctl enable spin
  - systemctl start spin
